services:
  backend:
    build:
      context: ../tokka-labs-backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "3333:3333"  # Expose backend on port 3333
    networks:
      - app-network

  frontend:
    build:
      context: ../tokka-labs-frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "5234:5234"  # Expose frontend on port 5234
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
